import HatchetClient from "@hatchet-dev/typescript-sdk";
import{createHmac}from"node:crypto";
const h=HatchetClient.init(),U=Bun.env.SUPABASE_URL,S=Bun.env.HATCHET_DISPATCH_BRIDGE_SECRET||"";
if(!U)throw Error("SUPABASE_URL missing");
const sl=(n:number)=>new Promise(r=>setTimeout(r,n));
const tok=(j:string,t:any)=>String(t||"")||(S?createHmac("sha256",S+":etribe-hatchet-job-callback-v1").update(j).digest("hex"):(()=>{throw Error("HATCHET_DISPATCH_BRIDGE_SECRET missing")})());
async function ctl(o:string,j:string,t:string,b:any={}){const r=await fetch(`${U}/functions/v1/hatchet-control`,{method:"POST",headers:{"content-type":"application/json","x-hatchet-job-token":t},body:JSON.stringify({op:o,job_id:j,...b})}),x=await r.text();let d:any;try{d=x?JSON.parse(x):null}catch{d={raw:x}}if(!r.ok||d?.error||d?.status==="error")throw Error(`ctl_${o}:${String(d?.error||d?.raw||r.status).slice(0,400)}`);return d}
async function pkt(j:string,t:string){let e="not_ready";for(let k=0;k<20;k++){try{const d=await ctl("packet",j,t);if(d?.packet?.orchestrator_run_id)return d.packet;e="missing_run"}catch(x){e=x instanceof Error?x.message:String(x)}await sl(300)}throw Error(`PACKET_NOT_READY:${j}:${e.slice(0,180)}`)}
const accept=h.task({name:"etribe-cloud-acceptance-v2",retries:2,fn:async(i:any)=>({status:"ok",worker:"ETRIBE_CLOUD_02",probe:i?.probe||"accept"})});
const retry=h.task({name:"etribe-retry-acceptance-v2",retries:2,fn:async(i:any,c:any)=>{const n=c.retryCount();console.log(`RETRY_ATTEMPT retry_count=${n}`);if(n===0)throw Error("intentional_acceptance_failure");return{status:"ok_after_retry",worker:"ETRIBE_CLOUD_02",probe:i?.probe||"retry",retryCount:n}}});
const idem={strategy:"status",expression:"input.idempotency_key",fallbackTtlMs:3600000};
const noop=h.task({name:"etribe-cloud-noop-job-v2",retries:2,idempotency:idem,fn:async(i:any)=>{const j=String(i?.job_id||"");if(!j)throw Error("JOB_ID_MISSING");const t=tok(j,i?.callback_token),p=await pkt(j,t);if(p.status==="succeeded")return p.result_ref||{status:"already_succeeded"};if(p.status==="dead_letter")throw Error(`JOB_DEAD:${j}`);const result={status:"cloud_noop_success",worker:"ETRIBE_CLOUD_02",job_id:j,completed_at:new Date().toISOString()},a=await ctl("success",j,t,{hatchet_run_id:p.orchestrator_run_id,result});if(a?.recorded!==true)throw Error(`SUCCESS_NOT_RECORDED:${j}`);return result}});
const drive=h.task({name:"etribe-drive-job-v2",retries:2,idempotency:idem,fn:async(i:any,c:any)=>{const j=String(i?.job_id||"");if(!j)throw Error("JOB_ID_MISSING");const t=tok(j,i?.callback_token),n=c.retryCount(),p=await pkt(j,t);if(p.status==="succeeded")return p.result_ref||{status:"already_succeeded"};if(p.status==="dead_letter")throw Error(`JOB_DEAD:${j}`);try{const a=await ctl("execute_adapter",j,t),result={status:"drive_execution_success",worker:"GOOGLE_DRIVE_WORKER",job_id:j,adapter_result:a?.result??a,completed_at:new Date().toISOString()},z=await ctl("success",j,t,{hatchet_run_id:p.orchestrator_run_id,result});if(z?.recorded!==true)throw Error(`SUCCESS_NOT_RECORDED:${j}`);return result}catch(x){const m=x instanceof Error?x.message:String(x);if(n>=2&&p.status==="running"&&!m.startsWith("SUCCESS_NOT_RECORDED"))try{await ctl("failure",j,t,{hatchet_run_id:p.orchestrator_run_id,error_code:"DRIVE_ADAPTER_FAILED",error_detail:m.slice(0,1000)})}catch{}throw x}}});
Bun.serve({port:Number(Bun.env.PORT||3000),fetch:(q:Request)=>new URL(q.url).pathname==="/health"?Response.json({status:"ok",worker:"ETRIBE_CLOUD_02"}):Response.json({error:"not_found"},{status:404})});
async function tests(){await sl(5000);try{const r=await accept.runNoWait({probe:"railway-ts-roundtrip"});console.log(`ACCEPTANCE_PASS run_id=${await r.getWorkflowRunId()} result=${JSON.stringify(await r.result())}`)}catch(e){console.error("ACCEPTANCE_FAIL",e)}try{const r=await retry.runNoWait({probe:"railway-ts-retry"});console.log(`RETRY_PASS run_id=${await r.getWorkflowRunId()} result=${JSON.stringify(await r.result())}`)}catch(e){console.error("RETRY_FAIL",e)}}
const slots=Math.max(1,Math.min(5,Number(Bun.env.HATCHET_WORKER_SLOTS||5))),w=await h.worker("ETRIBE_CLOUD_02",{workflows:[accept,retry,noop,drive],slots});console.log(`Starting ETRIBE_CLOUD_02 TypeScript worker slots=${slots}`);tests();await w.start();
